# Build settings
plugins:
  - jekyll-paginate

# Dependencies
markdown:         kramdown


# Permalinks
permalink:        pretty

# Setup
title:            Dongle Tech Blog
tagline:          'A Jekyll theme'
description:      'A Tech Blog'
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
paginate:         5



# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
